/*jsl:import foundation/core/base.js*/
/*jsl:import foundation/additions/es5-additions.js*/
/*jsl:import foundation/additions/string-additions.js*/
/*jsl:import foundation/additions/array-additions.js*/
/*jsl:import foundation/additions/array-additions-ie.js*/
/*jsl:import foundation/additions/function-additions.js*/
/*jsl:import foundation/core/set.js*/
/*jsl:import foundation/additions/object-additions.js*/
/*jsl:import foundation/additions/regex-additions.js*/
/*jsl:import foundation/core/oop.js*/
